@hostname = localhost
@port = 4000
@version = api
@module = auth
@host = {{hostname}}:{{port}}/{{version}}/{{module}}
@contentType = application/json

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwYTY1ZDQxNy03MDY1LTRjODktOTlkOC02YTY5ODM5MTFiNDMiLCJpYXQiOjE3MzQ3MzE3NjIsImV4cCI6MTczNDczMjY2Mn0.qLRNEyj1Vmnv1ghYLtX_wVsKLPVD6oXOdmMN4NGww78
@email = adam13nas@gmail.com
@password = Pchela90

### 1. Login

POST http://{{host}}/login
Content-Type: {{contentType}}

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### 2. Register
POST http://{{host}}/register
Content-Type: {{contentType}}

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### 3. Register Confirm
POST http://{{host}}/register/confirm
Content-Type: {{contentType}}

{
  "token": "48ade80b-b97c-4c39-8aca-738963c20968"
}

### 4. Refresh token
POST http://{{host}}/refresh
Content-Type: {{contentType}}

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwYTY1ZDQxNy03MDY1LTRjODktOTlkOC02YTY5ODM5MTFiNDMiLCJpYXQiOjE3MzQ3MzE2OTIsImV4cCI6MTczNTMzNjQ5Mn0.gkIiZgO8LuOzoENFJjdeMyyV-3clEK8F3pM4GiACwn4"
}

### 5. Logout
POST http://{{host}}/logout
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIwYTY1ZDQxNy03MDY1LTRjODktOTlkOC02YTY5ODM5MTFiNDMiLCJpYXQiOjE3MzQ3MzE3NjIsImV4cCI6MTczNDczMjY2Mn0.qLRNEyj1Vmnv1ghYLtX_wVsKLPVD6oXOdmMN4NGww78"
}


### 6. Password reset request
POST http://{{host}}/password/request
Content-Type: {{contentType}}

{
  "email": "{{email}}"
}

### 7. Password reset
POST http://{{host}}/password/reset
Content-Type: {{contentType}}

{
  "password": "{{password}}",
  "token": "70b36eab-5861-4a3b-a6b2-27c5c6dfac22"
}
