@hostname = localhost
@port = 4000
@version = api
@module = auth
@host = {{hostname}}:{{port}}/{{version}}/{{module}}
@contentType = application/json

@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlMmY3YzZhMC05NmM3LTRmNWItYjVmMi1kYTY4NTljOTBjNzYiLCJpYXQiOjE3MzM5NTgzMTgsImV4cCI6MTczMzk1OTIxOH0.26PrbPaz3SznfLHxmrG7SixeWb53aThRCxwhc4liOcQ
@email = adam13nas@gmail.com
@password = Pchela90

### 1. Login

POST http://{{host}}/login
Content-Type: {{contentType}}

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### 2. Register
POST http://{{host}}/register
Content-Type: {{contentType}}

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### 3. Register Confirm
POST http://{{host}}/register/confirm
Content-Type: {{contentType}}

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkYW0xM25hc0BnbWFpbC5jb20iLCJzY29wZSI6InNpZ251cCIsImlhdCI6MTcxMjg3MDU4OSwiZXhwIjoxNzEzNDc1Mzg5LCJpc3MiOiJtYXBzY2FsIn0.XURylLNG-ABQgU8nTcHvVms_plmlrBcbQ0lGc-U6o5U"
}

### 4. Refresh token
POST http://{{host}}/refresh
Content-Type: {{contentType}}

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlMmY3YzZhMC05NmM3LTRmNWItYjVmMi1kYTY4NTljOTBjNzYiLCJpYXQiOjE3MzM5NTk4NTMsImV4cCI6MTczNDU2NDY1M30.Pm560amxvSgIDNCaVco21fkj6fduo6E_tpqQ6waO6Og"
}

### 5. Logout
POST http://{{host}}/logout
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJlMmY3YzZhMC05NmM3LTRmNWItYjVmMi1kYTY4NTljOTBjNzYiLCJpYXQiOjE3MzM5NTgzMTgsImV4cCI6MTczMzk1OTIxOH0.26PrbPaz3SznfLHxmrG7SixeWb53aThRCxwhc4liOcQ"
}


### 6. Password reset request
POST http://{{host}}/password/request
Content-Type: {{contentType}}

{
  "email": "{{email}}"
}

### 7. Password reset
POST http://{{host}}/password/reset
Content-Type: {{contentType}}

{
  "password": "{{password}}",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkYW0xM25hc0BnbWFpbC5jb20iLCJzY29wZSI6InBhc3N3b3JkLXJlc2V0IiwiaGFzaCI6IjMyNzRhZWFkIiwiaWF0IjoxNzEyODc0ODkzLCJleHAiOjE3MTI5NjEyOTMsImlzcyI6Im1hcHNjYWwifQ.gIMmBAglkJkc3_QEKVtZl27Cf2_5RyTfUoF_t1EhOB0"
}
