@hostname = localhost
@port = 4000
@version = api
@module = teams
@host = {{hostname}}:{{port}}/{{version}}/{{module}}
@contentType = application/json
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ZTE1ZWNlZC1hYzg3LTQwM2ItYjAwNi00MDM4NjRjOGUyMjEiLCJpYXQiOjE3MzUzMzUxNTcsImV4cCI6MTczNTM0NTk1N30.kfeBQtg7XlW9f53rA-DZm0LCJxBI-W7VFMkqzAi3Gh8

### 1. Get all teams

GET http://{{host}}
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}


### 2. Create team

POST http://{{host}}
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "name": "Team 2",
  "description": "Team 2 description",
  "workspaceId": "d28b48e7-e6c3-4a8c-87a2-1621a2357814"
}


### 3. Delete Team

DELETE http://{{host}}/0508d8b5-6233-461e-a1a7-e3e786e8ab7a
Authorization: Bearer {{authToken}}
