@hostname = localhost
@port = 4000
@version = api
@module = users
@host = {{hostname}}:{{port}}/{{version}}/{{module}}
@contentType = application/json
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ZTE1ZWNlZC1hYzg3LTQwM2ItYjAwNi00MDM4NjRjOGUyMjEiLCJpYXQiOjE3MzUwODE2MzMsImV4cCI6MTczNTA5MjQzM30.pkOX0oRQjj69Xjin8keyOCVUVBqXxqwTBvAmz2hB9gM

### 1. Me

GET http://{{host}}/me
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

### 2. Update user

PATCH http://{{host}}/me
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "workspaceId": "d28b48e7-e6c3-4a8c-87a2-1621a2357814"
}

### 2. Users (find all)

GET http://{{host}}/?page=1&limit=20&fields=username&fields=full_name&fields=email&sort=email:asc&fields=id
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

### 7. Invite member

POST http://{{host}}/invite
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "email": "tazo90@gmail.com"
}

### 8. Accept invite

POST http://{{host}}/invite/accept
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFkYW0xM25hc0BnbWFpbC5jb20iLCJzY29wZSI6Imludml0ZSIsImlhdCI6MTcxMzAzNTMxNiwiZXhwIjoxNzEzNjQwMTE2LCJpc3MiOiJtYXBzY2FsIn0.zHAaNpMOV6ipSVVxYTmmHhQFxL2eybkKSJt3_JExLjY",
  "password": "test"
}

### 9. Resend invite

POST http://{{host}}/invite/resend
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "userId": 8,
  "subject": "Hello Invite",
  "url": "http://mapscal.com/admin/"
}

### 10. Revoke invite

POST http://{{host}}/invite/revoke
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "userId": 8
}
