@hostname = localhost
@port = 4000
@version = api
@module = workspaces
@host = {{hostname}}:{{port}}/{{version}}/{{module}}
@contentType = application/json
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ZTE1ZWNlZC1hYzg3LTQwM2ItYjAwNi00MDM4NjRjOGUyMjEiLCJpYXQiOjE3MzUwNzk4MDcsImV4cCI6MTczNTA5MDYwN30.7V1MtDO7Y-du5-HPe_fcQJrknwy06E08mxBwdBsoGR4

### 1. Get all user workspaces

GET http://{{host}}
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}


### 2. Create workspace

POST http://{{host}}
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "name": "workspace 2",
  "description": "10"
}


### 3. Delete workspace

DELETE http://{{host}}/132d8644-320c-41e3-924c-5b9a1ef2f01a
Authorization: Bearer {{authToken}}
