@hostname = localhost
@port = 4000
@version = api
@module = workspaces
@host = {{hostname}}:{{port}}/{{version}}/{{module}}
@contentType = application/json
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ZTE1ZWNlZC1hYzg3LTQwM2ItYjAwNi00MDM4NjRjOGUyMjEiLCJpYXQiOjE3MzQ5MDgzMTgsImV4cCI6MTczNDkwOTIxOH0.gW5Q5IQHNRukp_0dxa3-Ab_6wBB80vy4QAVQ3SFPhWY

### 1. Get all user workspaces

GET http://{{host}}
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}


### 2. Create workspace

POST http://{{host}}
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "name": "workspace 22",
  "description": "10"
}


### 3. Delete workspace

DELETE http://{{host}}/132d8644-320c-41e3-924c-5b9a1ef2f01a
Authorization: Bearer {{authToken}}

### 6. Set current workspace

PUT http://{{host}}/set-current-workspace
Content-Type: {{contentType}}
Authorization: Bearer {{authToken}}

{
  "workspace_id": 39
}
